FROM openjdk:17
EXPOSE 8097
ADD target/tawasalna-MaintenanceAgent-0.0.1-SNAPSHOT.jar tawasalna-MaintenanceAgent-0.0.1-SNAPSHOT.jar
COPY /tawasalna-MaintenanceAgent/target/tawasalna-MaintenanceAgent-0.0.1-SNAPSHOT.jar tawasalna-MaintenanceAgent-0.0.1-SNAPSHOT.jar
COPY /shared/target/shared-0.0.2-SNAPSHOT.jar shared-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","tawasalna-MaintenanceAgent-0.0.1-SNAPSHOT.jar"]