FROM openjdk:17
EXPOSE 8200
ADD target/tawasalna-crisis-0.0.1-SNAPSHOT.jar tawasalna-crisis-0.0.1-SNAPSHOT.jar
COPY /tawasalna-crisis/target/tawasalna-crisis-0.0.1-SNAPSHOT.jar tawasalna-crisis-0.0.1-SNAPSHOT.jar
COPY /shared/target/shared-0.0.2-SNAPSHOT.jar shared-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","tawasalna-crisis-0.0.1-SNAPSHOT.jar"]