FROM openjdk:17
EXPOSE 9003
ADD target/Management-Coordination-0.0.1-SNAPSHOT.jar Management-Coordination-0.0.1-SNAPSHOT.jar
COPY /Management-Coordination/target/Management-Coordination-0.0.1-SNAPSHOT.jar Management-Coordination-0.0.1-SNAPSHOT.jar
COPY /shared/target/shared-0.0.2-SNAPSHOT.jar shared-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Management-Coordination-0.0.1-SNAPSHOT.jar"]