FROM openjdk:17
EXPOSE 9004
ADD target/tawasalna-security-safety-0.0.1-SNAPSHOT.jar tawasalna-security-safety-0.0.1-SNAPSHOT.jar
COPY /tawasalna-security-safety/target/tawasalna-security-safety-0.0.1-SNAPSHOT.jar tawasalna-security-safety-0.0.1-SNAPSHOT.jar
COPY /shared/target/shared-0.0.2-SNAPSHOT.jar shared-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","tawasalna-security-safety-0.0.1-SNAPSHOT.jar"]