FROM openjdk:17

WORKDIR /app

EXPOSE 8080

COPY /tawasalna-administration/target/tawasalna-administration-0.0.1-SNAPSHOT.jar tawasalna-administration-0.0.1-SNAPSHOT.jar




 CMD ["java", "-jar", "tawasalna-administration-0.0.1-SNAPSHOT.jar"]
