FROM openjdk:17
EXPOSE 8070
ADD target/tawasalna-operations-0.0.1-SNAPSHOT.jar tawasalna-operations-0.0.1-SNAPSHOT.jar
COPY /tawasalna-operations/target/tawasalna-operations-0.0.1-SNAPSHOT.jar tawasalna-operations-0.0.1-SNAPSHOT.jar
COPY /shared/target/shared-0.0.2-SNAPSHOT.jar shared-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","tawasalna-operations-0.0.1-SNAPSHOT.jar"]