FROM openjdk:17
EXPOSE 8016
ADD target/tawasalna-facilities-management-0.0.1-SNAPSHOT.jar tawasalna-facilities-management-0.0.1-SNAPSHOT.jar
COPY /tawasalna-facilities-management/target/tawasalna-facilities-management-0.0.1-SNAPSHOT.jar tawasalna-facilities-management-0.0.1-SNAPSHOT.jar
COPY /shared/target/shared-0.0.2-SNAPSHOT.jar shared-0.0.2-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","tawasalna-facilities-management-0.0.1-SNAPSHOT.jar"]